### PR TITLE
Use correct remote version.json

### PR DESCRIPTION
**Pull request by jpedro-barbosa**

### CODE REVIEW

**Comment by staabm** [comment]
Fixed in https://github.com/staabm/xhprof.io thx

**Comment by jpedro-barbosa** [comment]
Thanks.

When do you think this will be merged into the official one? gajus/xhprof.io

**Comment by staabm** [comment]
Last commit in this repo is from 2013...

**Comment by jpedro-barbosa** [comment]
LOL and sigh :/

**Comment by gajus** [comment]
> Last commit in this repo is from 2013... Feel free to use my fork. See Readme there.

Most of my clients have moved to Node.js, thus I have little time to contribute to PHP community. Nonetheless, PHP 7 is a long awaited development. I plan to be using it when a stable version comes out.

Somewhat surprisingly, the community interest in xhprof.io remained active throughout these years and to this day there are no worthy alternatives that I know of (please update me if you know any).

I have refrained from accepting any pull requests primarily because the platform is not broken and I am afraid that accepting changes can do more harm than good (suppose something goes wrong, I would not have time to troubleshoot). Besides, this library would use a complete overhaul starting with test driven development that would de-risk accepting new pull requests.

Finally, I have seen that @staabm is doing a great job maintaining https://github.com/staabm/xhprof.io and I don't mind him at all (somewhat persistently) promoting his own fork. Furthermore, if @staabm would like to become the maintainer of the original package, I'd be happy to allow that.

**Comment by gajus** [comment]
Regarding this specific issue, server side version checking should be rooted out of the code. I have no idea what made me think this is a good idea to begin with.

**Comment by jpedro-barbosa** [comment]
> Regarding this specific issue, server side version checking should be rooted out of the code.

Actually due to proxy problems this is exactly what I've done.

**Comment by staabm** [comment]
>Somewhat surprisingly, the community interest in xhprof.io remained active throughout these years and to this day there are no worthy alternatives that I know of (please update me if you know any).

right, this is still the case.

>I have refrained from accepting any pull requests primarily because the platform is not broken and I am afraid that accepting changes can do more harm than good (suppose something goes wrong, I would not have time to troubleshoot). Besides, this library would use a complete overhaul starting with test driven development that would de-risk accepting new pull requests.

cant agree more. I am also dont using this tool on my own in the last months but using blackfire.io when required. Nevertheless ist a awesome tool built by gajus.

> Finally, I have seen that @staabm is doing a great job maintaining https://github.com/staabm/xhprof.io and I don't mind him at all (somewhat persistently) promoting his own fork.

Its not about promoting my fork, but pointing the users to a maintained fork.

>Furthermore, if @staabm would like to become the maintainer of the original package, I'd be happy to allow that.

As I dont use the tool that regularly I dont want to invest the time to move/merge all the commits/adaptions made until now.

**Comment by jpedro-barbosa** [comment]
FYI #74 created.

**Pull request closed without merging**
