### PR TITLE
Follow redirects

### PR DESCRIPTION
**Pull request by jpedro-barbosa**
Because:

```bash
$ curl -i https://raw.github.com/gajus/xhprof.io/master/version.json
HTTP/1.1 200 Connection established

HTTP/1.1 301 Moved Permanently
Location: https://raw.githubusercontent.com/gajus/xhprof.io/master/version.json
Content-Length: 0
Accept-Ranges: bytes
Date: Wed, 17 Jun 2015 18:08:30 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-lhr6335-LHR
X-Cache: MISS
X-Cache-Hits: 0
Vary: Accept-Encoding
```

### CODE REVIEW

**Comment by staabm** [comment]
You should change the url instead of following the redirect

**Comment by jpedro-barbosa** [comment]
Why? What if github changes the url again?

**Comment by staabm** [comment]
Then we change again ;)

**Comment by jpedro-barbosa** [comment]
Replaced by https://github.com/gajus/xhprof.io/pull/73. Closing.

**Pull request closed without merging**
